# Generated by Django 6.0.1 on 2026-01-09 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва тега')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='HEX колір')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендована')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Переглядів')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайків')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-published_at'],
            },
        ),
    ]
